# Copyright (c) 2023- All neurodb_dart_driver authors. All rights reserved.
#
# This source code is licensed under Apache 2.0 License.

name: neurodb_dart_driver
description: Neurodb driver writen by dart, which help flutter app connect to neurodb server.
version: 0.0.1+2
homepage: https://github.com/dudu-ltd/neurodb_dart_driver

environment:
  sdk: '>=2.19.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
